[on-prem] initial poc
draios/instruqt-assets pull request #111
Opened 2023-08-23 09:52 UTC by pabloopez

2023-08-24 09:24 UTC, Jujuyeh requested changes

2023-08-24 09:24 UTC, Jujuyeh commented on common/prepare-track/init.sh
> +            HELM_REGION_ID=au1
```suggestion
            HELM_REGION_ID=custom
```

2023-08-24 09:48 UTC, pabloopez commented on common/prepare-track/init.sh
> +            HELM_REGION_ID=au1
Good catch, thank you!

2023-08-24 09:50 UTC, Jujuyeh requested changes

2023-08-24 09:50 UTC, Jujuyeh commented on common/prepare-track/init.sh
> +            REGION="On Premises - onprem"
```suggestion
            if [[ -n "$ON_PREM_ENDPOINT" ]]
            then
                REGION="On Premises - onprem"
            else
                echo "${REGION_N} is not a valid an option."
                select_region
            fi
```

2023-08-24 09:50 UTC, Jujuyeh commented on common/prepare-track/init.sh
> +    echo "   6) On Premises - onprem"
```suggestion
    if [[ -n "$ON_PREM_ENDPOINT" ]]
    then
        echo "   6) On Premises - onprem"
    fi
```

2023-08-24 10:04 UTC, pabloopez commented
@Jujuyeh thanks for the review. I think this is ready to be merged, but before we do, I'd like to test the latest changes with a new on-prem env. The one that I used expired yesterday. @mateobur can you spin up a new one so we can test this and merge?

2023-09-08 14:56 UTC, pabloopez commented on common/prepare-track/install_with_helm.sh
> +    --set rapidResponse.rapidResponse.sslVerifyCertificate=flase \
```suggestion
    --set rapidResponse.rapidResponse.sslVerifyCertificate=false \
```

2023-09-08 14:57 UTC, pabloopez commented
Update on the comment above: tested and working fine. Ready to merge @Jujuyeh can you review and approve?

2023-09-18 20:14 UTC, pabloopez commented on common/prepare-track/init.sh
> +    echo "  -x <on_prem_endpoint>       In case an on-prem backend is used, set here the endpoint value."
```suggestion
    echo "  --on-prem <on_prem_endpoint>       In case an on-prem backend is used, set here the endpoint value."                     
```

2023-09-18 20:14 UTC, pabloopez commented on common/prepare-track/init.sh
> +            -x) # on-prem backend
```suggestion
            --on-prem) # on-prem backend
```

2023-10-20 10:37 UTC, merged