Init test condition
draios/instruqt-assets pull request #37
Opened 2022-01-05 14:50 UTC by pabloopez

# Instruqt automation: `init.sh` aware of being run within a `instruqt track test`

This PR is the first step to enable automated tests for Sysdig labs at instruqt.

This is a WIP. One of the migrated labs (knps lab) already includes some basic scripts in place and I want to start testing in parallel this feature and review that all test are green. Consider that this is not the final/desired state of this and there are some blockers and things to improve:
- Instruqt has not implemented a way to pass ENV_VARS to the `instruqt test track` command yet. The FR request is done but is not implemented yet. To work around this problem, current keys are base64 encoded and decoded when used. Next iteration will store the keys as GH Secrets for our automation or just as ENV_VARS when running test locally.
- It removes nginx proxy, as we do not have a way to directly test the embeded Sysdig Dashboards UI. 
- Another limitation: the existing test account is linked to a particular region. When extending this tests other regions should be considered. But right now, it is enough to enable basic testing.

I request to merge this to main, as it is working fine with no errors and it does not influence normal execution of the`init.sh` job. The approach is not the best one, as it just replaces every request for user input (`read -p "message" VAR`) with a condition to check for a test-aware variable.

2022-01-05 15:34 UTC, pabloopez commented
This is not required in any way, but if any of you is interested in accessing the test account, you can use:
`https://us2.app.sysdig.com/`
`team-training+instruqt@sysdig.com`

And ask for bitwarden/lastpass key. Or Slack, I don't mind as this is just for testing.

2022-01-05 19:13 UTC, pmusa requested changes
- The .DS_Store file should be removed from the PR. I suggest we also include a line to the `.gitignore` file to remove them in the future.

The rest looks good to me. I left a minor comment.

2022-01-05 19:13 UTC, pmusa commented on common/prepare-track/init.sh
> +        systemctl stop nginx
I mean, what is the impact if we don't have this if statement?

2022-01-07 08:37 UTC, pabloopez commented on common/prepare-track/init.sh
> +        systemctl stop nginx
No impact at all if we leave it as it is. 

The reason to kill the nginx service is that in *test* mode there's no way to check what's in the tabs.

2022-01-07 08:50 UTC, merged

2022-01-07 15:30 UTC, pmusa commented on common/prepare-track/init.sh
> +        systemctl stop nginx
I don't see an advantage in killing nginx. I would keep it.

2022-01-10 09:53 UTC, pabloopez commented on common/prepare-track/init.sh
> +        systemctl stop nginx
Neither I do in keeping it there, but let's keep it. It is not a big deal.

2022-01-10 09:54 UTC, pabloopez commented on common/prepare-track/init.sh
> +        systemctl stop nginx
https://github.com/draios/instruqt-assets/pull/38