[init.sh] debug + logic improvements
draios/instruqt-assets pull request #83
Opened 2023-01-23 10:38 UTC by pabloopez

helper branch to debug automation tests for monitoring-integrations PR: draios/instruqt#463

2023-01-23 15:13 UTC, pabloopez commented
collector recheck example logs:

```
2023-01-23T15:12:42Z igj0l2unrzbg INFO: setup-server:   Checking agent collector logs...  not found
2023-01-23T15:12:45Z igj0l2unrzbg INFO: setup-server:   Checking agent collector logs...  found. Sysdig Agent successfully installed.
2023-01-23T15:12:45Z igj0l2unrzbg INFO: setup-server:   Sysdig Agent cluster.name: insq_2023-01-23__17_11
```

2023-01-25 14:08 UTC, pmusa requested changes
I left one comment. Everything else looks good to me.

2023-01-25 14:31 UTC, pabloopez commented on common/prepare-track/init.sh
> +        while [ -z ${FOUND_COLLECTOR} ] && [ $attempt -le $MAX_ATTEMPTS ]
Thanks Pablo, you are right about:
>  increment on every loop.

But the non-reset was intentional, I don't think we have to increase the number of attempts to wait for the collector.

2023-01-25 15:03 UTC, pabloopez commented on common/prepare-track/init.sh
> +        while [ -z ${FOUND_COLLECTOR} ] && [ $attempt -le $MAX_ATTEMPTS ]
@pmusa follow up on slack conversation

2023-01-25 15:15 UTC, pmusa commented on common/prepare-track/init.sh
> +        while [ -z ${FOUND_COLLECTOR} ] && [ $attempt -le $MAX_ATTEMPTS ]
I think that having the second loop run or not based on where the increment is placed in the code is not a good solution. I would rather have the loops merged since they have the same conditions or the counter reset.

2023-01-25 15:16 UTC, pmusa approved these changes
I am not convinced by this solutions, but Pablo asked me to approve like this...

I think that having the second loop run or not based on where the increment is placed in the code is not a good solution. I would rather have the loops merged since they have the same conditions or the counter reset.

2023-01-25 20:07 UTC, pabloopez commented
> I am not convinced by this solutions, but Pablo asked me to approve like this...
btw, we don't enforce approval before merging here.

> I think that having the second loop run or not based on where the increment is placed in the code is not a good solution. I would rather have the loops merged since they have the same conditions or the counter reset.
Oh, boy.

2023-01-26 08:59 UTC, pabloopez commented
retest of the script running now here: https://github.com/draios/instruqt/actions/runs/4013650530

2023-01-26 21:25 UTC, pabloopez commented
@pmusa friendly reminder, I see you mentioning the PR in other channels but somehow missed the new changes

2023-01-26 21:32 UTC, pmusa approved these changes
lgtm

2023-01-26 22:03 UTC, pabloopez commented
ty pal

2023-01-26 22:03 UTC, merged